#pragma once

#include <glm/glm.hpp>
#include <memory>
#include <string>
#include <vector>

namespace opticsketch {

// Represents a single beam segment (3D line)
class Beam {
public:
    Beam(const std::string& beamId = "");
    
    std::string id;
    std::string label;
    
    // Beam segment endpoints
    glm::vec3 start;
    glm::vec3 end;
    
    // Visual properties
    glm::vec3 color{1.0f, 0.0f, 0.0f};  // Default red for laser beams
    float width = 2.0f;                  // Line width in pixels
    bool visible = true;
    int layer = 0;

    // Ray tracing
    bool isTraced = false;             // true if generated by ray tracer
    std::string sourceElementId;       // source element that spawned this traced beam
    float intensity = 1.0f;            // ray intensity (0..1), used for alpha modulation

    // Gaussian beam parameters (optional)
    bool isGaussian = false;
    float waistW0 = 0.001f;        // Beam waist radius in meters (default 1mm)
    float wavelength = 633e-9f;     // Wavelength in meters (default 633nm HeNe)
    float waistPosition = 0.0f;     // Normalized [0,1] position of waist along beam (0=start)

    float getRayleighRange() const;     // zR = pi * w0^2 / lambda
    float getDivergenceAngle() const;   // theta = lambda / (pi * w0)
    float beamRadiusAt(float z) const;  // w(z) = w0 * sqrt(1 + (z/zR)^2)
    
    // Get beam direction (normalized)
    glm::vec3 getDirection() const;
    
    // Get beam length
    float getLength() const;
    
    // Deep-copy into a new Beam with a new ID
    std::unique_ptr<Beam> clone() const;

    // Generate unique ID
    static std::string generateId();
};

} // namespace opticsketch
